### ISSUE TITLE
Filtering on University Center Plugin

### ISSUE THREAD

**Issue by charlesjdillon** [washingtonstateuniversity/swwrc.wsu.edu#14]
Need to list and filter publications, people, projects, an entity by tag. This can be on the same page just need different headings.

On the top of the page those labels should be in a checkbox that would be checked by default to show them displayed, but when unchecked and checked they toggle through the different labels.

They have most of the content entered excluding people (/person) which will be Staff, affiliates, and advisory committee.

**Comment by philcable** [comment]
@charlesjdillon Would you please provide a few URLs of the pages they would like this feature to be included on? I'm not quite able to figure it from the description. Thanks in advance!
