### ISSUE TITLE
Searching through the site and/or UC plugin

### ISSUE THREAD

**Issue by charlesjdillon** [washingtonstateuniversity/swwrc.wsu.edu#15]
They want to be able to have a search on the page that works for the different types of content through the UC data. If this is site wide or just UC plugin data works either way.

**Comment by philcable** [comment]
@charlesjdillon Is the search form going to be included in the site header? Or do we need to provide a shortcode for one? Or both?

**Comment by philcable** [comment]
@charlesjdillon What should search results look like?

**Comment by charlesjdillon** [comment]
Let's have a plan for both.

**Comment by charlesjdillon** [comment]
@philcable I was going to design it based on what content was provided. I know we want to pull people's images in.
